prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/plugins/region_type/markdown.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_sampleappfooter.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_display_source.sql
@@application/plugin_settings.sql
@@application/shared_components/workflow/task_definitions/appraisal_employee_input.sql
@@application/shared_components/workflow/task_definitions/appraisal_manager_input.sql
@@application/shared_components/workflow/task_definitions/appraisal_vp_review.sql
@@application/shared_components/workflow/task_definitions/bank_account_change.sql
@@application/shared_components/workflow/task_definitions/job_change.sql
@@application/shared_components/workflow/task_definitions/laptop_approval.sql
@@application/shared_components/workflow/task_definitions/laptop_delivered.sql
@@application/shared_components/workflow/task_definitions/salary_change.sql
@@application/shared_components/workflow/workflows/employee_appraisal.sql
@@application/shared_components/workflow/workflows/laptop_procurement.sql
@@application/shared_components/workflow/workflows/laptop_request.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/user_interface.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/abouttheapprovalsfeature_md.sql
@@application/shared_components/files/aboutthesampleapplication_md.sql
@@application/shared_components/files/abouttheworkflowfeature_md.sql
@@application/shared_components/files/usingthesample_md.sql
@@application/shared_components/files/app_css.sql
@@application/shared_components/files/app_min_css.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/readme_appraisalworkflow_jpg.sql
@@application/shared_components/files/readme_approvals_jpg.sql
@@application/shared_components/files/readme_datamodel_jpg.sql
@@application/shared_components/files/readme_employees_jpg.sql
@@application/shared_components/files/readme_employees2_jpg.sql
@@application/shared_components/files/readme_laptopordermgmt_jpg.sql
@@application/shared_components/files/readme_laptopprocurementworkflow_jpg.sql
@@application/shared_components/files/readme_laptopworkflow_jpg.sql
@@application/shared_components/files/readme_salapprovers_jpg.sql
@@application/shared_components/files/readme_selfeval_jpg.sql
@@application/shared_components/files/readme_taskviews_jpg.sql
@@application/shared_components/files/readme_workflowviews_jpg.sql
@@application/shared_components/security/authorizations/operations_team.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/current_user_empno.sql
@@application/shared_components/logic/application_computations/current_user_empno.sql
@@application/shared_components/logic/application_computations/p29_show_for_subordinates.sql
@@application/shared_components/logic/application_computations/p8_show_only_subordinates.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/all_enames_lov.sql
@@application/shared_components/user_interface/lovs/approval_task_lov.sql
@@application/shared_components/user_interface/lovs/available_laptop_types.sql
@@application/shared_components/user_interface/lovs/dept_dname.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/distinct_job_codes_lov.sql
@@application/shared_components/user_interface/lovs/eba_demo_conf_emp_lov.sql
@@application/shared_components/user_interface/lovs/emp_ename.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_due.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_initiated.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_priority.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_state.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_type.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/workflow_charts_lov_time_unit.sql
@@application/shared_components/user_interface/lovs/workflow_console_lov_initiated.sql
@@application/shared_components/user_interface/lovs/workflow_console_lov_workflow_state.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/email/templates/job_change_notification.sql
@@application/shared_components/email/templates/laptop_delivered_notification.sql
@@application/shared_components/security/authentications/demo_purposes_only_custom_auth_scheme.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_10010.sql
@@application/end_environment.sql
